// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.2
// source: protos/movie-service/movie.proto

package movieservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 😇
type Genres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genre string `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
}

func (x *Genres) Reset() {
	*x = Genres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_movie_service_movie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Genres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genres) ProtoMessage() {}

func (x *Genres) ProtoReflect() protoreflect.Message {
	mi := &file_protos_movie_service_movie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genres.ProtoReflect.Descriptor instead.
func (*Genres) Descriptor() ([]byte, []int) {
	return file_protos_movie_service_movie_proto_rawDescGZIP(), []int{0}
}

func (x *Genres) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

type AddMovieReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieName          string    `protobuf:"bytes,1,opt,name=movie_name,json=movieName,proto3" json:"movie_name,omitempty"`
	AgeLimit           int32     `protobuf:"varint,2,opt,name=age_limit,json=ageLimit,proto3" json:"age_limit,omitempty"`
	BackgroundImageUrl string    `protobuf:"bytes,3,opt,name=background_image_url,json=backgroundImageUrl,proto3" json:"background_image_url,omitempty"`
	MovieUrl           string    `protobuf:"bytes,4,opt,name=movie_url,json=movieUrl,proto3" json:"movie_url,omitempty"`
	Studio             string    `protobuf:"bytes,5,opt,name=studio,proto3" json:"studio,omitempty"`
	Bio                string    `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	Genres             []*Genres `protobuf:"bytes,7,rep,name=genres,proto3" json:"genres,omitempty"`
	Language           string    `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *AddMovieReq) Reset() {
	*x = AddMovieReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_movie_service_movie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMovieReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMovieReq) ProtoMessage() {}

func (x *AddMovieReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_movie_service_movie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMovieReq.ProtoReflect.Descriptor instead.
func (*AddMovieReq) Descriptor() ([]byte, []int) {
	return file_protos_movie_service_movie_proto_rawDescGZIP(), []int{1}
}

func (x *AddMovieReq) GetMovieName() string {
	if x != nil {
		return x.MovieName
	}
	return ""
}

func (x *AddMovieReq) GetAgeLimit() int32 {
	if x != nil {
		return x.AgeLimit
	}
	return 0
}

func (x *AddMovieReq) GetBackgroundImageUrl() string {
	if x != nil {
		return x.BackgroundImageUrl
	}
	return ""
}

func (x *AddMovieReq) GetMovieUrl() string {
	if x != nil {
		return x.MovieUrl
	}
	return ""
}

func (x *AddMovieReq) GetStudio() string {
	if x != nil {
		return x.Studio
	}
	return ""
}

func (x *AddMovieReq) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *AddMovieReq) GetGenres() []*Genres {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *AddMovieReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AddMovieRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddMovieRes) Reset() {
	*x = AddMovieRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_movie_service_movie_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMovieRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMovieRes) ProtoMessage() {}

func (x *AddMovieRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_movie_service_movie_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMovieRes.ProtoReflect.Descriptor instead.
func (*AddMovieRes) Descriptor() ([]byte, []int) {
	return file_protos_movie_service_movie_proto_rawDescGZIP(), []int{2}
}

func (x *AddMovieRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMovieByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMovieByIdReq) Reset() {
	*x = GetMovieByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_movie_service_movie_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieByIdReq) ProtoMessage() {}

func (x *GetMovieByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_movie_service_movie_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieByIdReq.ProtoReflect.Descriptor instead.
func (*GetMovieByIdReq) Descriptor() ([]byte, []int) {
	return file_protos_movie_service_movie_proto_rawDescGZIP(), []int{3}
}

func (x *GetMovieByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMovieByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MovieName          string    `protobuf:"bytes,2,opt,name=movie_name,json=movieName,proto3" json:"movie_name,omitempty"`
	AgeLimit           int32     `protobuf:"varint,3,opt,name=age_limit,json=ageLimit,proto3" json:"age_limit,omitempty"`
	BackgroundImageUrl string    `protobuf:"bytes,4,opt,name=background_image_url,json=backgroundImageUrl,proto3" json:"background_image_url,omitempty"`
	MovieUrl           string    `protobuf:"bytes,5,opt,name=movie_url,json=movieUrl,proto3" json:"movie_url,omitempty"`
	Studio             string    `protobuf:"bytes,6,opt,name=studio,proto3" json:"studio,omitempty"`
	Bio                string    `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	Genres             []*Genres `protobuf:"bytes,8,rep,name=genres,proto3" json:"genres,omitempty"`
	Language           string    `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	CreatedAt          string    `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string    `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *GetMovieByIdRes) Reset() {
	*x = GetMovieByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_movie_service_movie_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieByIdRes) ProtoMessage() {}

func (x *GetMovieByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_movie_service_movie_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieByIdRes.ProtoReflect.Descriptor instead.
func (*GetMovieByIdRes) Descriptor() ([]byte, []int) {
	return file_protos_movie_service_movie_proto_rawDescGZIP(), []int{4}
}

func (x *GetMovieByIdRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMovieByIdRes) GetMovieName() string {
	if x != nil {
		return x.MovieName
	}
	return ""
}

func (x *GetMovieByIdRes) GetAgeLimit() int32 {
	if x != nil {
		return x.AgeLimit
	}
	return 0
}

func (x *GetMovieByIdRes) GetBackgroundImageUrl() string {
	if x != nil {
		return x.BackgroundImageUrl
	}
	return ""
}

func (x *GetMovieByIdRes) GetMovieUrl() string {
	if x != nil {
		return x.MovieUrl
	}
	return ""
}

func (x *GetMovieByIdRes) GetStudio() string {
	if x != nil {
		return x.Studio
	}
	return ""
}

func (x *GetMovieByIdRes) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *GetMovieByIdRes) GetGenres() []*Genres {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *GetMovieByIdRes) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetMovieByIdRes) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetMovieByIdRes) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UpdateMovieReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MovieName          string    `protobuf:"bytes,2,opt,name=movie_name,json=movieName,proto3" json:"movie_name,omitempty"`
	AgeLimit           int32     `protobuf:"varint,3,opt,name=age_limit,json=ageLimit,proto3" json:"age_limit,omitempty"`
	BackgroundImageUrl string    `protobuf:"bytes,4,opt,name=background_image_url,json=backgroundImageUrl,proto3" json:"background_image_url,omitempty"`
	MovieUrl           string    `protobuf:"bytes,5,opt,name=movie_url,json=movieUrl,proto3" json:"movie_url,omitempty"`
	Studio             string    `protobuf:"bytes,6,opt,name=studio,proto3" json:"studio,omitempty"`
	Bio                string    `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	Genres             []*Genres `protobuf:"bytes,8,rep,name=genres,proto3" json:"genres,omitempty"`
	Language           string    `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *UpdateMovieReq) Reset() {
	*x = UpdateMovieReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_movie_service_movie_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMovieReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieReq) ProtoMessage() {}

func (x *UpdateMovieReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_movie_service_movie_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieReq.ProtoReflect.Descriptor instead.
func (*UpdateMovieReq) Descriptor() ([]byte, []int) {
	return file_protos_movie_service_movie_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMovieReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMovieReq) GetMovieName() string {
	if x != nil {
		return x.MovieName
	}
	return ""
}

func (x *UpdateMovieReq) GetAgeLimit() int32 {
	if x != nil {
		return x.AgeLimit
	}
	return 0
}

func (x *UpdateMovieReq) GetBackgroundImageUrl() string {
	if x != nil {
		return x.BackgroundImageUrl
	}
	return ""
}

func (x *UpdateMovieReq) GetMovieUrl() string {
	if x != nil {
		return x.MovieUrl
	}
	return ""
}

func (x *UpdateMovieReq) GetStudio() string {
	if x != nil {
		return x.Studio
	}
	return ""
}

func (x *UpdateMovieReq) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateMovieReq) GetGenres() []*Genres {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *UpdateMovieReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type UpdateMovieRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpdateMovieRes) Reset() {
	*x = UpdateMovieRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_movie_service_movie_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMovieRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieRes) ProtoMessage() {}

func (x *UpdateMovieRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_movie_service_movie_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieRes.ProtoReflect.Descriptor instead.
func (*UpdateMovieRes) Descriptor() ([]byte, []int) {
	return file_protos_movie_service_movie_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMovieRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteMovieReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMovieReq) Reset() {
	*x = DeleteMovieReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_movie_service_movie_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMovieReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieReq) ProtoMessage() {}

func (x *DeleteMovieReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_movie_service_movie_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieReq.ProtoReflect.Descriptor instead.
func (*DeleteMovieReq) Descriptor() ([]byte, []int) {
	return file_protos_movie_service_movie_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMovieReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMovieRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteMovieRes) Reset() {
	*x = DeleteMovieRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_movie_service_movie_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMovieRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieRes) ProtoMessage() {}

func (x *DeleteMovieRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_movie_service_movie_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieRes.ProtoReflect.Descriptor instead.
func (*DeleteMovieRes) Descriptor() ([]byte, []int) {
	return file_protos_movie_service_movie_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMovieRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveMovieReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveMovieReq) Reset() {
	*x = RemoveMovieReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_movie_service_movie_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMovieReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMovieReq) ProtoMessage() {}

func (x *RemoveMovieReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_movie_service_movie_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMovieReq.ProtoReflect.Descriptor instead.
func (*RemoveMovieReq) Descriptor() ([]byte, []int) {
	return file_protos_movie_service_movie_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveMovieReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveMovieRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RemoveMovieRes) Reset() {
	*x = RemoveMovieRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_movie_service_movie_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMovieRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMovieRes) ProtoMessage() {}

func (x *RemoveMovieRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_movie_service_movie_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMovieRes.ProtoReflect.Descriptor instead.
func (*RemoveMovieRes) Descriptor() ([]byte, []int) {
	return file_protos_movie_service_movie_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveMovieRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAllMoviesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MovieName          string    `protobuf:"bytes,2,opt,name=movie_name,json=movieName,proto3" json:"movie_name,omitempty"`
	AgeLimit           int32     `protobuf:"varint,3,opt,name=age_limit,json=ageLimit,proto3" json:"age_limit,omitempty"`
	BackgroundImageUrl string    `protobuf:"bytes,4,opt,name=background_image_url,json=backgroundImageUrl,proto3" json:"background_image_url,omitempty"`
	MovieUrl           string    `protobuf:"bytes,5,opt,name=movie_url,json=movieUrl,proto3" json:"movie_url,omitempty"`
	Studio             string    `protobuf:"bytes,6,opt,name=studio,proto3" json:"studio,omitempty"`
	Bio                string    `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	Genres             []*Genres `protobuf:"bytes,8,rep,name=genres,proto3" json:"genres,omitempty"`
	Language           string    `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	Limit              int32     `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset             int32     `protobuf:"varint,11,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetAllMoviesReq) Reset() {
	*x = GetAllMoviesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_movie_service_movie_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllMoviesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMoviesReq) ProtoMessage() {}

func (x *GetAllMoviesReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_movie_service_movie_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMoviesReq.ProtoReflect.Descriptor instead.
func (*GetAllMoviesReq) Descriptor() ([]byte, []int) {
	return file_protos_movie_service_movie_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllMoviesReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAllMoviesReq) GetMovieName() string {
	if x != nil {
		return x.MovieName
	}
	return ""
}

func (x *GetAllMoviesReq) GetAgeLimit() int32 {
	if x != nil {
		return x.AgeLimit
	}
	return 0
}

func (x *GetAllMoviesReq) GetBackgroundImageUrl() string {
	if x != nil {
		return x.BackgroundImageUrl
	}
	return ""
}

func (x *GetAllMoviesReq) GetMovieUrl() string {
	if x != nil {
		return x.MovieUrl
	}
	return ""
}

func (x *GetAllMoviesReq) GetStudio() string {
	if x != nil {
		return x.Studio
	}
	return ""
}

func (x *GetAllMoviesReq) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *GetAllMoviesReq) GetGenres() []*Genres {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *GetAllMoviesReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetAllMoviesReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllMoviesReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAllMoviesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Movies     []*GetMovieByIdRes `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	TotalCount int32              `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *GetAllMoviesRes) Reset() {
	*x = GetAllMoviesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_movie_service_movie_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllMoviesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMoviesRes) ProtoMessage() {}

func (x *GetAllMoviesRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_movie_service_movie_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMoviesRes.ProtoReflect.Descriptor instead.
func (*GetAllMoviesRes) Descriptor() ([]byte, []int) {
	return file_protos_movie_service_movie_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllMoviesRes) GetMovies() []*GetMovieByIdRes {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *GetAllMoviesRes) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_protos_movie_service_movie_proto protoreflect.FileDescriptor

var file_protos_movie_service_movie_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x1e, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x22, 0x8c, 0x02, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x67, 0x65, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x30, 0x0a, 0x14,
	0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x62, 0x61, 0x63, 0x6b,
	0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75,
	0x64, 0x69, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x62, 0x69, 0x6f, 0x12, 0x2c, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x52, 0x06, 0x67, 0x65, 0x6e,
	0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22,
	0x27, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xde, 0x02, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x61, 0x67, 0x65, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x62,
	0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x62, 0x61, 0x63, 0x6b, 0x67,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a,
	0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x64,
	0x69, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x62, 0x69, 0x6f, 0x12, 0x2c, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x9f, 0x02, 0x0a,
	0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x61, 0x67, 0x65, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x62,
	0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x62, 0x61, 0x63, 0x6b, 0x67,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a,
	0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x64,
	0x69, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x62, 0x69, 0x6f, 0x12, 0x2c, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0x2a,
	0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x20, 0x0a, 0x0e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x20, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x0e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xce, 0x02, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x67, 0x65,
	0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x67,
	0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x76, 0x69,
	0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x62, 0x69, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x6f, 0x12,
	0x2c, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x6e, 0x72, 0x65, 0x73, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x69, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x06, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x52, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x32, 0xcd, 0x03, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12,
	0x19, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41,
	0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x52, 0x65, 0x73, 0x12, 0x4c, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x12, 0x49, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x12, 0x1c, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x1c, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x12, 0x49,
	0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x1c, 0x2e,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x12, 0x49, 0x0a, 0x0b, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x1c, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x4c, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x42, 0x20, 0x5a, 0x1e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_movie_service_movie_proto_rawDescOnce sync.Once
	file_protos_movie_service_movie_proto_rawDescData = file_protos_movie_service_movie_proto_rawDesc
)

func file_protos_movie_service_movie_proto_rawDescGZIP() []byte {
	file_protos_movie_service_movie_proto_rawDescOnce.Do(func() {
		file_protos_movie_service_movie_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_movie_service_movie_proto_rawDescData)
	})
	return file_protos_movie_service_movie_proto_rawDescData
}

var file_protos_movie_service_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protos_movie_service_movie_proto_goTypes = []interface{}{
	(*Genres)(nil),          // 0: movieservice.Genres
	(*AddMovieReq)(nil),     // 1: movieservice.AddMovieReq
	(*AddMovieRes)(nil),     // 2: movieservice.AddMovieRes
	(*GetMovieByIdReq)(nil), // 3: movieservice.GetMovieByIdReq
	(*GetMovieByIdRes)(nil), // 4: movieservice.GetMovieByIdRes
	(*UpdateMovieReq)(nil),  // 5: movieservice.UpdateMovieReq
	(*UpdateMovieRes)(nil),  // 6: movieservice.UpdateMovieRes
	(*DeleteMovieReq)(nil),  // 7: movieservice.DeleteMovieReq
	(*DeleteMovieRes)(nil),  // 8: movieservice.DeleteMovieRes
	(*RemoveMovieReq)(nil),  // 9: movieservice.RemoveMovieReq
	(*RemoveMovieRes)(nil),  // 10: movieservice.RemoveMovieRes
	(*GetAllMoviesReq)(nil), // 11: movieservice.GetAllMoviesReq
	(*GetAllMoviesRes)(nil), // 12: movieservice.GetAllMoviesRes
}
var file_protos_movie_service_movie_proto_depIdxs = []int32{
	0,  // 0: movieservice.AddMovieReq.genres:type_name -> movieservice.Genres
	0,  // 1: movieservice.GetMovieByIdRes.genres:type_name -> movieservice.Genres
	0,  // 2: movieservice.UpdateMovieReq.genres:type_name -> movieservice.Genres
	0,  // 3: movieservice.GetAllMoviesReq.genres:type_name -> movieservice.Genres
	4,  // 4: movieservice.GetAllMoviesRes.movies:type_name -> movieservice.GetMovieByIdRes
	1,  // 5: movieservice.MovieService.AddMovie:input_type -> movieservice.AddMovieReq
	3,  // 6: movieservice.MovieService.GetMovieById:input_type -> movieservice.GetMovieByIdReq
	5,  // 7: movieservice.MovieService.UpdateMovie:input_type -> movieservice.UpdateMovieReq
	7,  // 8: movieservice.MovieService.DeleteMovie:input_type -> movieservice.DeleteMovieReq
	9,  // 9: movieservice.MovieService.RemoveMovie:input_type -> movieservice.RemoveMovieReq
	11, // 10: movieservice.MovieService.GetAllMovies:input_type -> movieservice.GetAllMoviesReq
	2,  // 11: movieservice.MovieService.AddMovie:output_type -> movieservice.AddMovieRes
	4,  // 12: movieservice.MovieService.GetMovieById:output_type -> movieservice.GetMovieByIdRes
	6,  // 13: movieservice.MovieService.UpdateMovie:output_type -> movieservice.UpdateMovieRes
	8,  // 14: movieservice.MovieService.DeleteMovie:output_type -> movieservice.DeleteMovieRes
	10, // 15: movieservice.MovieService.RemoveMovie:output_type -> movieservice.RemoveMovieRes
	12, // 16: movieservice.MovieService.GetAllMovies:output_type -> movieservice.GetAllMoviesRes
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protos_movie_service_movie_proto_init() }
func file_protos_movie_service_movie_proto_init() {
	if File_protos_movie_service_movie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_movie_service_movie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Genres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_movie_service_movie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMovieReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_movie_service_movie_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMovieRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_movie_service_movie_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_movie_service_movie_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_movie_service_movie_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMovieReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_movie_service_movie_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMovieRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_movie_service_movie_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMovieReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_movie_service_movie_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMovieRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_movie_service_movie_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMovieReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_movie_service_movie_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMovieRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_movie_service_movie_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllMoviesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_movie_service_movie_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllMoviesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_movie_service_movie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_movie_service_movie_proto_goTypes,
		DependencyIndexes: file_protos_movie_service_movie_proto_depIdxs,
		MessageInfos:      file_protos_movie_service_movie_proto_msgTypes,
	}.Build()
	File_protos_movie_service_movie_proto = out.File
	file_protos_movie_service_movie_proto_rawDesc = nil
	file_protos_movie_service_movie_proto_goTypes = nil
	file_protos_movie_service_movie_proto_depIdxs = nil
}
